### ISSUE TITLE
Incompatible PHP requirement

### ISSUE THREAD

**Issue by frank-f5w** [mtrdesign/s3-logs-parser#1]
Thank you for creating and publishing s3-logs-parser!

My dev machine already runs PHP 8.0 and I ran into an issue when asking composer to include your package in my project.
The error is displayed below.

$ composer require mtrdesign/s3-logs-parser

  [InvalidArgumentException]
  Package mtrdesign/s3-logs-parser has a PHP requirement incompatible with
  your PHP version, PHP extensions and Composer version

**Comment by frank-f5w** [comment]
To add, my current composer.json contains:

```
{
    "require": {
        "symfony/yaml": "^5.2",
        "tightenco/collect": "^8.17",
        "aws/aws-sdk-php": "^3.171"
    }
}
```

**Comment by akolevutd** [comment]
Hey @fsluijs we pushed a new Package release (1.0.3) and the issue should be now solved. Can you check it, please? 

- https://packagist.org/packages/mtrdesign/s3-logs-parser#1.0.3

```
Requires:
    php: ^7.4|^8.0
    ext-json: *
    aws/aws-sdk-php: ^3.100
    nesbot/carbon: ^2.19
```

**Comment by frank-f5w** [comment]
Wonderful, that now works fine for me. Thanks very much!
