### ISSUE TITLE
add instructions for running the test suite to README

### ISSUE THREAD

**Issue by apurvis** [mtrdesign/s3-logs-parser#4]
i'm trying to add a simple feature to read from local disk on my fork but have no idea how to run the tests.  i know like 10+ programming languages and PHP is not one of them.  

having the instructions in the README will help future PHP ignorant folks like myself add features/fix bugs/etc.

**Comment by akolevutd** [comment]
Hey @apurvis and thanks for this request. I've just added some instructions in the readme - https://github.com/mtrdesign/s3-logs-parser#contributing
